config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  devise_for :patients
  root 'welcome#index'
  resources :access_requests, only: [:index, :new, :create]
  resources :companies do
    member do
      get :dashboard
      post :request_access
    end
  end
  resources :patients do 
    member do
      get :dashboard
    end
  end

  resources :lab_results do
    collection do
      get :my_results
      post :analyze
    end
    member do
      post :share
      delete 'shares/:share_id', to: 'lab_results#revoke_share', as: :revoke_share
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to "HealthID", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if patient_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_patient_path(current_patient), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Lab Results", my_results_lab_results_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <span class="navbar-text text-light me-3">
              <%= current_patient.email %>
            </span>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_patient_session_path, 
                method: :delete, 
                class: "btn btn-outline-light", 
                data: { turbo_method: :delete } %>
          </li>
        <% elsif company_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_company_path(current_company), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Issue Lab Result", new_lab_result_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <span class="navbar-text text-light me-3">
              <%= current_company.name || current_company.email %>
            </span>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_company_session_path, 
                method: :delete, 
                class: "btn btn-outline-light", 
                data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Patient Login", new_patient_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Provider Login", new_company_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>